### ISSUE TITLE
Why do u use Spring cloud for microservice

### ISSUE THREAD

**Issue by HelloTo4x** [2ndHG/Simple-Mall#1]
Hi, i am reading your repository, i have a question, why do u use Spring cloud for microservice instead of Kubernetes, or AWS/GCP(cloud platform). Thank u so much

**Comment by 2ndHG** [comment]
Hi, Do you mean Spring boot? I think those are some abandoned solutions.

So this project is a college project. At the beginning the teacher of our team gave us some resources to build a mall service. He give us https://github.com/macrozheng/mall and my teammate tried to build it. But since we were bad and we couldn't use some services that provided by Chinese company(Couldn't register an account), we failed with it. Finally because I love craft things with my hands so we decided to make a simpler mall service by ourselves. We used XAMPP.

BTW, didn't expect somebody will read this mess, I feel sorry for hurting your eyes and brain.😥

**Comment by HelloTo4x** [comment]
No, i mean why don't you use K8S ? You use Eureka for discovery service, Ribbon for Load Balance, Hystrix for circuit breaker, right ? why don't u use Kubernetes for it simpler ?

**Comment by 2ndHG** [comment]
Sorry, I don't know what is Eureka and Ribbon. where did you see them?

**Comment by HelloTo4x** [comment]
sorry, i am wrong, but why do you use XAMPP instead of Spring boot

**Comment by HelloTo4x** [comment]
i mean this
![here](https://user-images.githubusercontent.com/80832558/171547173-88bb43d7-ce23-4ea2-8f78-c0a444076c1c.PNG)

**Comment by 2ndHG** [comment]
I don't know haha. I guess we were just so bad at understanding a system. So we chose XAMPP, it's easy, execute it and it runs.
We can create a simpler system and handle all user's methods(register, upload merch, etc.) by ourselves.

**Comment by HelloTo4x** [comment]
tk you <3
